---
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-cache

      - run:
          name: Fetch dependencies
          command: ./gradlew dependencies --refresh-dependencies

      - run:
          name: Run gradle build
          command: ./gradlew clean installdist --stacktrace

      - save_cache:
          key: gradle-cache
          paths:
            - ~/.gradle

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push Docker image
          command: |
            chmod +x ./scripts/*.sh
            case ${CIRCLE_BRANCH} in
                master)
                    ./gradlew publish --stacktrace
                    ./scripts/docker-build.sh latest
                    ;;
                develop)
                    ./gradlew publish --stacktrace
                    ./scripts/docker-build.sh beta
                    ;;
                *)
                    echo "Publish not required for branch: ${CIRCLE_BRANCH}"
                    ;;
            esac
